
/**
 * Normalizes Bengali text for better fuzzy matching.
 * Handles common spelling variations and removes diacritics that often vary.
 */
export const normalizeBengali = (text: string): string => {
  if (!text) return "";
  
  return text
    .replace(/ী/g, "ি") // Long ee to short i
    .replace(/ূ/g, "ু") // Long uu to short u
    .replace(/ণ/g, "ন") // Murdhanya Na to Dantya Na
    .replace(/ষ/g, "স") // Murdhanya Sa to Dantya Sa
    .replace(/শ/g, "স") // Talabya Sa to Dantya Sa
    .replace(/ড়/g, "র") // Ra variations
    .replace(/ঢ়/g, "র")
    .replace(/য়/g, "য়")
    .replace(/ৎ/g, "ত")
    .replace(/[\u09BC]/g, "") // Remove nukta
    .trim()
    .toLowerCase();
};

/**
 * Comprehensive transliteration from Romanized Bengali to Bengali script.
 * Covers common Bible verse references, spiritual terms, and everyday Bengali words.
 */
export const transliterateToBengali = (text: string): string => {
  const mapping: { [key: string]: string } = {
    // Pronouns & Basic
    "ami": "আমি",
    "tumi": "তুমি",
    "she": "সে",
    "tara": "তারা",
    "amra": "আমরা",
    "tomra": "তোমরা",
    "apni": "আপনি",
    
    // Bible Books - Gospels
    "matthew": "মথি",
    "mathew": "মথি",
    "matti": "মথি",
    "mark": "মার্ক",
    "luke": "লুকা",
    "luk": "লুকা",
    "john": "যোহন",
    "johann": "যোহন",
    "jhon": "যোহন",
    
    // Bible Books - Old Testament
    "genesis": "আদিপুস্তক",
    "exodus": "যাত্রাপুস্তক",
    "leviticus": "লেবীয়",
    "numbers": "গণনা",
    "deuteronomy": "দ্বিতীয় বিধান",
    "joshua": "যোশু",
    "judges": "বিচারক",
    "ruth": "রূথ",
    "samuel": "শমূয়েল",
    "kings": "রাজা",
    "chronicles": "বংশাবল",
    "ezra": "এজরা",
    "nehemiah": "নেহেমিয়া",
    "esther": "এস্থের",
    "job": "আয়োব",
    "psalm": "গীতসংহিতা",
    "psalms": "গীতসংহিতা",
    "proverbs": "হিতোপদেশ",
    "ecclesiastes": "উপদেশক",
    "song": "পরম歌",
    "isaiah": "যিশাইয়",
    "jeremiah": "耶利米",
    "lamentations": "বিলাপ",
    "ezekiel": "যিহিষ্কেল",
    "daniel": "দানিয়েল",
    "hosea": "হোশেয়",
    "joel": "যোয়েল",
    "amos": "আমোস",
    "obadiah": "ওবদিয়াহ",
    "jonah": "যোনাহ",
    "micah": "মীখা",
    "nahum": "নাহূম",
    "habakkuk": "হাবাকুক",
    "zephaniah": "সফনিয়াহ",
    "haggai": "হগয়",
    "zechariah": "জাকারিয়াহ",
    "malachi": "মালাখি",
    
    // Bible Books - New Testament (Other)
    "acts": "প্রেরিত",
    "romans": "রোমীয়",
    "rom": "রোমীয়",
    "corinthians": "করিন্থীয়",
    "cor": "করিন্থীয়",
    "galatians": "গালাতীয়",
    "gal": "গালাতীয়",
    "ephesians": "ইফিসীয়",
    "eph": "ইফিসীয়",
    "philippians": "ফিলিপীয়",
    "phil": "�িলিপীয়",
    "colossians": "কলসীয়",
    "col": "কলসীয়",
    "thessalonians": "থেসালনীকীয়",
    "thess": "থেসালনীকীয়",
    "timothy": "তীমথি",
    "tim": "তীমথি",
    "titus": "তীতুস",
    "philemon": "ফিলেমন",
    "hebrews": "হিব্রু",
    "heb": "হব্রু",
    "james": "ইয়াকূব",
    "peter": "পত্র",
    "peters": "পত্র",
    "john epistle": "যোহন",
    "jude": "যুদা",
    "revelation": "প্রকাশ",
    
    // Numbers with Bengali
    "1": "১",
    "2": "২",
    "3": "৩",
    "4": "৪",
    "5": "৫",
    "6": "৬",
    "7": "৭",
    "8": "৮",
    "9": "৯",
    "10": "১০",
    "11": "১১",
    "12": "১২",
    "13": "১৩",
    "14": "১৪",
    "15": "১৫",
    "16": "১৬",
    "17": "১৭",
    "18": "১৮",
    "19": "১৯",
    "20": "২০",
    "21": "২১",
    "22": "২২",
    "23": "২৩",
    "24": "২৪",
    "25": "২৫",
    "26": "২৬",
    "27": "২৭",
    "28": "২৮",
    "29": "২৯",
    "30": "৩০",
    "31": "৩১",
    "32": "৩২",
    "33": "৩৩",
    "34": "৩৪",
    "35": "৩৫",
    "36": "৩৬",
    "37": "৩৭",
    "38": "৩৮",
    "39": "৩৯",
    "40": "৪০",
    "41": "৪১",
    "42": "৪২",
    "43": "৪৩",
    "44": "৪৪",
    "45": "৪৫",
    "46": "৪৬",
    "47": "৪৭",
    "48": "৪৮",
    "49": "৪৯",
    "50": "৫০",
    "51": "৫১",
    "52": "৫২",
    "53": "৫৩",
    "54": "৫৪",
    "55": "৫৫",
    "56": "৫৬",
    "57": "৫৭",
    "58": "৫৮",
    "59": "৫৯",
    "60": "৬০",
    "61": "৬১",
    "62": "৬২",
    "63": "৬৩",
    "64": "৬৪",
    "65": "৬৫",
    "66": "৬৬",
    "67": "৬৭",
    "68": "৬৮",
    "69": "৬৯",
    "70": "৭০",
    "71": "৭১",
    "72": "৭২",
    "73": "৭৩",
    "74": "৭৪",
    "75": "৭৫",
    "76": "৭৬",
    "77": "৭৭",
    "78": "৭৮",
    "79": "৭৯",
    "80": "৮০",
    "81": "৮১",
    "82": "৮২",
    "83": "৮৩",
    "84": "৮৪",
    "85": "৮৫",
    "86": "৮৬",
    "87": "৮৭",
    "88": "৮৮",
    "89": "৮৯",
    "90": "৯০",
    "91": "৯১",
    "92": "৯২",
    "93": "৯৩",
    "94": "৯৪",
    "95": "৯৫",
    "96": "৯৬",
    "97": "৯৭",
    "98": "৯৮",
    "99": "৯৯",
    "100": "১০০",
    
    // Common spiritual terms
    "shanti": "শান্তি",
    "shonti": "শান্তি",
    "mukti": "মুক্তি",
    "mokhti": "মুক্তি",
    "papo": "পাপ",
    "pap": "পাপ",
    "papa": "পাপ",
    "khoma": "ক্ষমা",
    "khomaa": "ক্ষমা",
    "bishwash": "বিশ্বাস",
    "bishwas": "বিশ্বাস",
    "prarthona": "প্রার্থনা",
    "prarthonaa": "প্রার্থনা",
    "pran": "প্রার্থনা",
    "iswar": "ঈশ্বর",
    "ishwar": "ঈশ্বর",
    "ishor": "ঈশ্বর",
    "allah": "আল্লাহ",
    "jishu": "যীশু",
    "jeshu": "যীশু",
    "jesus": "যীশু",
    "jisu": "যীশু",
    "mashi": "মশীহ",
    "christ": "খ্রিস্ট",
    "bible": "বাইবেল",
    "shahara": "সহস্র",
    "geet": "গীত",
    "git": "গীত",
    "geeti": "গীত",
    "shonhita": "সংহিতা",
    "sonhita": "সংহিতা",
    "prem": "প্রেম",
    "valobasha": "ভালোবাসা",
    "balobasha": "ভালোবাসা",
    "anugroho": "অনুগ্রহ",
    "onugroho": "অনুগ্রহ",
    "ashirbad": "আশীর্বাদ",
    "ashirbadon": "আশীর্বাদ",
    "dhormo": "ধর্ম",
    "dhorom": "ধর্ম",
    "shastro": "শাস্ত্র",
    "puran": "পুরুষ",
    "purush": "পুরুষ",
    "nari": "নারী",
    "naari": "নারী",
    
    // Emotions & States
    "dukho": "দুঃখ",
    "dukkho": "দুঃখ",
    "sukho": "সুখ",
    "sukkho": "সুখ",
    "khushi": "খুশি",
    "hosh": "আশা",
    "asha": "আশা",
    "bhay": "ভয়",
    "bhoy": "ভয়",
    "premik": "প্রেমিক",
    
    // Actions
    "bolo": "বলো",
    "koro": "করো",
    "dao": "দাও",
    "neuo": "নাও",
    "dekho": "দেখো",
    "shuno": "শোনো",
    "eso": "এসো",
    "jabo": "যাবো",
    "ashbo": "আসবো",
    
    // Days & Times
    "din": "দিন",
    "raat": "রাত",
    "shondha": "সন্ধ্যা",
    "bikal": "বিকাল",
    "dupur": "দুপুর",
    "sokal": "সকাল",
    "shaptahik": "সাপ্তাহিক",
    "bosor": "বছর",
    "mas": "মাস",
    
    // God attributes
    "bappa": "বাপা",
    "pita": "পিতা",
    "maa": "মা",
    "pitribhu": "পিতৃবু",
    "bhobon": "ভগবান",
    "bhagoban": "ভগবান",
    "shori": "সৃষ্টিকর্তা",
    "shristi": "সৃষ্টি",
    "prabhu": "প্রভু",
    "raja": "রাজা",
    
    // Fruits of Spirit
    "prem sahit": "প্রেমসহ",
    "ashi": "আশা",
    "dhairjo": "ধৈর্য",
    "dhir": "ধৈর্য",
    "bhalochinta": "ভালোচিন্তা",
    "bhalo": "ভালো",
    "matro": "মঙ্গল",
    
    // Common phrases
    "jhontu": "ঝন্টু",
    "jhont": "ঝন্ট",
    "kintu": "কিন্তু",
    "karone": "কারণে",
    "karon": "কারণ",
    "tahole": "তাহলে",
    "tah": "তাহ",
    "tari": "তারী",
    "ke": "কে",
    "theke": "থেকে",
    "ei": "এই",
    "oi": "ওই",
    "je": "যে",
    
    // Numerals - Bengali script
    "one": "১",
    "two": "২",
    "three": "৩",
    "four": "৪",
    "five": "৫",
    "six": "৬",
    "seven": "৭",
    "eight": "৮",
    "nine": "৯",
    "ten": "১০",
  };

  const words = text.toLowerCase().split(/\s+/);
  return words.map(word => {
    const cleanWord = word.replace(/[.,:;!?()"]/g, "");
    const matched = mapping[cleanWord] || word;
    return matched;
  }).join(" ");
};

/**
 * Pre-defined Bengali search index for common spiritual topics and verses.
 */
export const BENGALI_SEARCH_INDEX = [
  { reference: "গীতসংহিতা ২৩", themes: ["শান্তি", "সুরক্ষা", "ঈশ্বর"], text: "সদাপ্রভু আমার পালক, আমার অভাব হবে না।" },
  { reference: "যোহন ৩:১৬", themes: ["ভালোবাসা", "মুক্তি", "যীশু"], text: "কারণ ঈশ্বর জগতকে এমন প্রেম করিলেন যে আপনার একজাত পুত্রকে দান করিলেন।" },
  { reference: "১ করিন্থীয় ১৩", themes: ["প্রেম", "ভালোবাসা"], text: "প্রেম চিরসহিষ্ণু, প্রেম দয়াবান।" },
  { reference: "গীতসংহিতা ৯১", themes: ["নিরাপত্তা", "আশ্রয়"], text: "যিনি পরাৎপরের গুপ্তস্থানে বাস করেন।" },
  { reference: "মথি ৫:৩-১২", themes: ["আশীর্বচন", "সুখ"], text: "ধন্য তাহারা, যাহারা আত্মাতে দীনহীন।" },
  { reference: "রোমীয় ৮:২৮", themes: ["মঙ্গল", "উদ্দেশ্য"], text: "যাহারা ঈশ্বরকে প্রেম করে, তাহাদের মঙ্গলের নিমিত্ত সকলই একযোগে কার্য করিতেছে।" },
  { reference: "যিশাইয় ৪০:৩১", themes: ["শক্তি", "ধৈর্য"], text: "কিন্তু যাহারা সদাপ্রভুর অপেক্ষা করে, তাহারা নূতন শক্তি পাইবে।" },
  { reference: "হিতোপদেশ ৩:৫-৬", themes: ["নির্ভরতা", "পথপ্রদর্শন"], text: "তোমার সমস্ত চিত্তে সদাপ্রভুতে বিশ্বাস কর।" },
  { reference: "ফিলিপীয় ৪:১৩", themes: ["সামর্থ্য", "শক্তি"], text: "যিনি আমাকে শক্তি দেন, তাঁহার দ্বারা আমি সকলই করিতে পারি।" },
  { reference: "মথি ১১:২৮", themes: ["বিশ্রাম", "শান্তি"], text: "হে পরিশ্রান্ত ও ভারাক্রান্ত লোক সকল, আমার নিকটে আইস।" },
];
